### ISSUE TITLE
BadMethodCallException - Method setTransformer does not exist.

### ISSUE THREAD

**Issue by alexanderawitin** [yajra/laravel-datatables-fractal#1]
I can't get this plugin to work. I keep on getting a `Method setTransformer does not exist.` error.

Here's my code:

`config/app.php`
```php
<?php

return [
    // Omitted

    /*
     * Package Service Providers...
     */
    // Omitted
    Yajra\DataTables\DataTablesServiceProvider::class,
    Yajra\DataTables\FractalServiceProvider::class,

    // Omitted


    'aliases' => [
        // Omitted
        'DataTables' => Yajra\DataTables\Facades\DataTables::class,
    ];
]
```

`UserController.php`
```php
namespace App\Http\Controllers;

use App\Models\User;
use App\Transformers\EmployeeTransformer;
use DataTables;

class DailyTimeRecordController extends Controller
{
    public function getEmployees() {
        $employees = User::role('employee');

        return Datatables::eloquent($employees)
            ->setTransformer(new EmployeeTransformer)
            ->make()
    }
}
```

`EmployeeTransformer.php`
```php
namespace App\Transformers;

use App\Models\User;
use League\Fractal\TransformerAbstract;

class DailyTimeRecordsTransformer extends TransformerAbstract
{
    /**
     * A Fractal transformer.
     *
     * @param User $user
     * @return array
     */
    public function transform(User $user)
    {
        return [
            'full_name' => $user->full_name,
            'avatar' => $user->avatar,
            // Omitted
        ];
    }
}
```

Error Stacktrace:
`
[2017-09-12 18:17:07] local.ERROR: BadMethodCallException: Method setTransformer does not exist. in /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:74
Stack trace:
#0 /Users/alexanderawitin/Code/tymelog/app/Http/Controllers/UserController.php(45): Yajra\DataTables\DataTableAbstract->__call('setTransformer', Array)
#1 [internal function]: App\Http\Controllers\UserController->timeLogs(Object(Illuminate\Http\Request), NULL, NULL)
#2 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('timeLogs', Array)
#4 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\UserController), 'timeLogs')
#5 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#6 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#7 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#13 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#17 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#20 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Users/alexanderawitin/Code/tymelog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#35 /Users/alexanderawitin/Code/tymelog/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#36 /Users/alexanderawitin/.composer/vendor/laravel/valet/server.php(133): require('/Users/alexande...')
#37 {main}
`

Also, `php artisan vendor:publish --tag=datatables-fractal --force` don't seem to publish any file related to this package.
 

### System details

- Operating System: macOS Sierra 10.12.6
- PHP Version: v7.1.8
- Laravel Version: v5.4.36
- Laravel-Datatables Version: v8.0.3
- Laravel-Datatables-Fractal Version: v1.0.1

**Comment by yajra** [comment]
It is added via macroable trait. Not sure but maybe you are still using an older version?

```
return Datatables::eloquent($employees) // should be DataTable::eloquent()
```

Or maybe just a typo and is not the issue?

**Comment by alexanderawitin** [comment]
The casing for
```php
return Datatables::eloquent($employees)
```
is just a typo when I filed this issue. Since I didn't copy-paste my actual code.

I think this issue is related to the service provider not registering properly because when I run `php artisan vendor:publish --tag=datatables-fractal --force`, it just returns `Publishing complete.` and nothing else.
Unlike when I run `php artisan vendor:publish --tag=datatables --force` it returns `Copied File [/vendor/yajra/laravel-datatables-oracle/src/config/datatables.php] To [/config/datatables.php]
Publishing complete.`

**Comment by alexanderawitin** [comment]
It works now. I just emptied composer's cache and reinstalled all dependencies.
