### ISSUE TITLE
fractal and action buttons

### ISSUE THREAD

**Issue by swash13** [yajra/laravel-datatables-fractal#10]
### how to use fractal transformer and ->addColumn('action', 'admin.categories.datatables_actions'); together ?

```php
$dataTable = new EloquentDataTable($query);

        return $dataTable
            ->setTransformer(new CategoryTransformer())
            ->addColumn('action', 'admin.categories.datatables_actions');
```

If i user this - action buttons do not display. How to include them with the transformer ?

**Comment by BlackCaptainTR** [comment]
As mentioned in [documentation](https://yajrabox.com/docs/laravel-datatables/master/response-fractal) 
> When using tranformer, all response manipulations must be done via transformer. Thus `addColumn`,  `editColumn`, `removeColumn`, `setRowAttr`, `setClassAttr`, etc... should be avoided when using fractal.

You have to add `action` column to the `ProductTransformer`. You can achieve this by doing something like below.
```php
public function transform(Product $product){
    return [
        'id' => $product->id,
        'name' => $product->name,
        'sku' => $product->sku,
        'category' => $product->category->name,
        'price' => $product->price,
        'action' => view('admin.categories.datatables_actions')->with('id', $product->id)->render()
    ];
}
```
You can use rendered view with/without variables or raw string.
#### Note
If you don't use `render()` on view, you will get Object and it will be shown as `[Object object]` in HTML so don't forget to use `render()` on view.
