### ISSUE TITLE
Searching return empty

### ISSUE THREAD

**Issue by nubinter** [yajra/laravel-datatables-fractal#15]
### Summary of problem or feature request

Hello
It seems that searching the table always return empty if the data has been transform. How can I make the searching return the appropriate data while using transformer?

### System details

- Operating System Centos 6
- PHP Version PHP 7
- Laravel Version 5.6
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
Sorry for late response. You can only search on what was in the database. If the value was manipulated using the transformer, you would need to create a custom query that matches the transformed value.
