### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by BardoQi** [yajra/laravel-datatables-fractal#16]
### Summary of problem or feature request

  Problem 1
    - Can only install one of: league/fractal[0.17.0, 0.16.0].
    - Can only install one of: league/fractal[0.16.0, 0.17.0].
    - Can only install one of: league/fractal[0.16.0, 0.17.0].
    - yajra/laravel-datatables-fractal v1.0.0 requires league/fractal ^0.16 -> s
atisfiable by league/fractal[0.16.0].
    - Installation request for yajra/laravel-datatables-fractal 1.0 -> satisfiab
le by yajra/laravel-datatables-fractal[v1.0.0].
    - Installation request for league/fractal (locked at 0.17.0) -> satisfiable
by league/fractal[0.17.0].

Installation failed, reverting ./composer.json to its original content.

### System details

- Operating System
- PHP Version 7.1
- Laravel Version 5.5 
- Laravel-Datatables Version 8.0

**Comment by abdullah-abunada** [comment]
installation error!!

```
Problem 1
    - Can only install one of: league/fractal[0.17.0, 0.18.0].
    - Can only install one of: league/fractal[0.18.0, 0.17.0].
    - Can only install one of: league/fractal[0.17.0, 0.18.0].
    - yajra/laravel-datatables-fractal v1.4.0 requires league/fractal ^0.17.0 -> satisfiable by league/fractal[0.17.0].
    - Installation request for yajra/laravel-datatables-fractal ^1.4 -> satisfiable by yajra/laravel-datatables-fractal[v1.4.0].
    - Installation request for league/fractal (locked at 0.18.0) -> satisfiable by league/fractal[0.18.0].
```
