### ISSUE TITLE
Not supporting Laravel-DataTables-oracle [9.0] 

### ISSUE THREAD

**Issue by ahmedfathi1** [yajra/laravel-datatables-fractal#18]
### Summary of problem or feature request

Can't install `laravel-datatables-fractal` because it's require `yajra/laravel-datatables-oracle: 8.*`
and not supporting `yajra/laravel-datatables-oracle: 9.*`

when trying to install this package plugin
with `composer require yajra/laravel-datatables-fractal`
composer shows  error:  
> yajra/laravel-datatables-fractal v1.3.0 requires yajra/laravel-datatables-oracle 8.* 

- Operating System : Ubuntu 16.04
- PHP Version : 7.2
- Laravel Version : 5.9
- Laravel-Datatables Version : 9.0

**Comment by shopapps** [comment]
+1 👍for this :-)

**Comment by asivaneswaran** [comment]
Any updates on this? This is blocking my update process...
