### ISSUE TITLE
Not supported for laravel 9

### ISSUE THREAD

**Issue by hypervision-am** [yajra/laravel-datatables-fractal#27]
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yajra/laravel-datatables-fractal ^1.6 -> satisfiable by yajra/laravel-datatables-fractal[v1.6.0].
    - yajra/laravel-datatables-fractal v1.6.0 requires league/fractal ^0.19.0 -> found league/fractal[0.19, 0.19.1, 0.19.2] but the package is fixed to 0.20.x-dev (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require yajra/laravel-datatables-fractal:*" to figure out if any version is installable, or "composer require yajra/laravel-datatables-fractal:^2.1" if you know which you need.

How can I add yajra/laravel-datatables-fractal in laravel 9 ?

**Comment by hypervision-am** [comment]
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yajra/laravel-datatables-fractal ^1.6 -> satisfiable by yajra/laravel-datatables-fractal[v1.6.0].
    - yajra/laravel-datatables-fractal v1.6.0 requires league/fractal ^0.19.0 -> found league/fractal[0.19, 0.19.1, 0.19.2] but the package is fixed to 0.20.x-dev (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require yajra/laravel-datatables-fractal:*" to figure out if any version is installable, or "composer require yajra/laravel-datatables-fractal:^2.1" if you know which you need.

**Comment by yajra** [comment]
Fixed on v9.0.0 🍻

**Comment by hypervision-am** [comment]
Thank You Bro!!!!
